### ISSUE TITLE
Board compatibility. Power, status and reset pins

### ISSUE THREAD

**Issue by radar155** [blemasle/arduino-sim808#1]
Is [this](https://images-na.ssl-images-amazon.com/images/I/81ngkVXJS5L._SL1500_.jpg) board compatible with this library? I don't know where should I connect status, reset and power pin.

I modded the library to work only with Serial tx rx pin connections, but it would be nice to have powerOnOff methods and other nice things developed here.
I suppose "RTS" is for reset, but what about power and status pin?

**Comment by blemasle** [comment]
Hi @radar155 
RTS would be for "Ready To Send" I guess. You do have a RST pin on that board though.
Do you have the board source/website do I can check it out ?

Also, what you do you mean by "to have powerOnOff methods and other nice things developed here." ?

Status, reset and power pin are all used to control the Sim808 power in a reliable way, but if you don't need to turn it off (and as most of those premade boards bome with a permanent power on) you should be ok without using them.

As for powerOnOff, powerOff can be implemented without the power pin, but powerOn cannot.

**Comment by radar155** [comment]
[This](https://www.az-delivery.de/products/sim808-uno-mikrocontroller-bundle-sonderpreis?ls=en#description) is the website of the board. But I can't find nothing usefull in the user manual. They just suggests to use tx and rx pin  for serial comunication and a compatible library for sim900 (that I used but I don't like, thats why I am here).
Anyway this board's form factor is very comomon for sim808, there are other pretty identical board around from other companies.


I already tested your library without power reset and status pin, it can't work. It will fail on init function, where the first thing you do is a reset, followed by a "waitForReady" method that listen for a "RDY" message from the board. Without the reset command, you will never recieve the RDY message, or better, you will recieve it only when you power on the board by power button, and this is not comfortable while developing and pushing code all the day.

As i said, yesterday I modded the init method to work around this problem. But now I'm able to use with success the RST pin and the board reset method is properly working and the I can receive the "RDY" message without any code modding.

As I see, luckily ,power and status pin are not essential (if you dont need to power on/off programmatically).

**Comment by blemasle** [comment]
Yep, you're right about the status and pwr pins. The thing is I designed the library with full access to the sim808 controlling pins, and your kit do not seems to allow that. That's strange cause it seems to be based on evaluation kit that does have the header for the PWRKEY according to one of the document on the page you sent me.

I could change the library to try to made those pins optional but for the RDY thing, it is supposed to be the way you boot up the module, according to the datasheet of the SIM808 and many boards, including the Adafruit FONA which has its reset pin tied to the Arduino reset if I recall.

**Comment by radar155** [comment]
RST should be mandatory. PWR and STATUS could probably be optional, but they are very usefull for power management. I'm still investigating for my board's pins. The "D9" pin should be like a PWR, according to [this ](https://arduino.stackexchange.com/questions/24994/arduino-mega-sim808-gsm-gps-module-program-switch-on-without-pressing-push) post and in relative source (see comments).

**Comment by blemasle** [comment]
Yeah they could but they are both needed if using the power functions. Without the `STATUS` pin, `powerOnOff` would not be reliable in it's present implementation, and using it to power on might turn the SIM808 off and vice versa if your software and hardware states do not match.

**Comment by radar155** [comment]
I confirm D9 pin is working like a PWR pin. Now I recognized PWR and RST. I guess one of the other pin is the STATE, but for now i'm modding your library to get the status by checking if AT command returns OK. It's a little bit hacked but it works.

**Comment by blemasle** [comment]
It only reply `AT` to `AT` commands because echo is on on power on. I'm pretty sure this won't work for a device already powered on. Does `powered()` returns the correct result in all situations ?

**Comment by blemasle** [comment]
After some test, it does seems that the module always respond `OK` to `AT` commands. See #5
Thanks for all your help and suggestions !

**Comment by radar155** [comment]
Unfortunately it's not working. It's not related to your specific implementation, mine isn't working too. My problem is that when I turn off the module, after a while, it comes back on its own. This is happening with your code too. 
Do you experience the same problem? Try connecting only PWR and RST pins. Then test this program that with the sim808 module already turned on. Then, in the program, just init the library and power
```
void setup() {
  Serial.begin(SERIAL_BAUDRATE);
  Log.begin(LOG_LEVEL_NOTICE, &Serial);
  
  simSerial.begin(SIM808_BAUDRATE);
  sim808.begin(simSerial);

  Log.notice(F("Initializing SIM808..." NL));
  sim808.init();
  Log.notice(F("Powering off SIM808..." NL));
  sim808.powerOnOff(false);
  delay(100000);
  Log.notice(F("Powering on SIM808..." NL));
  sim808.powerOnOff(true);
}
```

What is happening to me is that the module correctly turns off. But before the 100 seconds delay could finish, it comes back (I can see that by watching leds.)

**Comment by blemasle** [comment]
@radar155  Any news regarding the `VCHG` suggestion ? :)

**Comment by blemasle** [comment]
Suggested improvments have been implemented by #5

**Comment by radar155** [comment]
I'm sorry about the delay, very busy. I don't understand you, but probably it's my fault. First: i can't find any `VBAT` or `VCHG` pin in my board. Check the link in my first post on this issue, there's an HD image of my board, can you tell me wich pin you are talking about? And also: how can i power the SIM808 without the DC? Should I power it from Arduino (powered itself by usb) with 3.4V Pin?

**Comment by blemasle** [comment]
`VBAT` or `VCHG` were referring to actual pins on the SIM808, not your board. I can't find any detailed schematics about your board but from looking at the picture, neither of those pins seems to be used. But it's really hard to tell for sure...

So, you should try to power the board with only the battery plugged in (without the DC jack). As a side note, you should never unplugged the battery. The SIM808 can spike at 2A, which most of the time wall chargers won't cope with.
