### ISSUE TITLE
Two serial ports

### ISSUE THREAD

**Issue by osiriust410** [blemasle/arduino-sim808#11]
Hi,
I'm using two serial ports, in this library I was looking for the **Serial.listen()** function or similar, but I can not find it. Please help me, or tell me how I add this function.
Thank you.

**Comment by blemasle** [comment]
Hi,

What do you mean by "using two serials ports" ? You can pass the `Serial` instance you want to use to the `SIM808` constructor, so you're free to call `listen()` on your instance at your convenience.

For instance, that's exactly what i'm doing when I put my [gps tracker to sleep](https://github.com/blemasle/gpstracker-firmware/blob/master/src/MainUnit.cpp#L27) to prevent an interrupt on one of the serial pins to woke up the device.
