### ISSUE TITLE
 warning: invalid conversion

### ISSUE THREAD

**Issue by ser** [blemasle/arduino-sim808#12]
hi, i am coming from python world to brutal arduino C and have an issue:
```
/home/ser/Arduino/gps-tracker-with-library/gps-tracker-with-library.ino: In function 'void loop()':
/home/ser/Arduino/gps-tracker-with-library/gps-tracker-with-library.ino:73:46: warning: invalid conversion from 'const __FlashStringHelper*' to '__StrPtr {aka __FlashStringHelper*}' [-fpermissive]
     if(status == SIM808GpsStatus::Fix) state = S_F("Normal");
                                              ^
/home/ser/Arduino/gps-tracker-with-library/gps-tracker-with-library.ino:74:16: warning: invalid conversion from 'const __FlashStringHelper*' to '__StrPtr {aka __FlashStringHelper*}' [-fpermissive]
     else state = S_F("Accurate");
                ^
```
it's your gps example with arduino 1.8.9 - is it something i should worry about? as i am not getting fix, which i am sure i should have, as i have it with simply accessing console without your library.

**Comment by blemasle** [comment]
Hi. You can ignore that warning, but I'll try to have a look and get it fixed :)
To dig into why you're not getting a fix, you can turn on console debugging by forcing `_SIM808_DEBUG` to `1`. See [here](https://github.com/blemasle/arduino-sim808#debugging)

This will print every command sent and their responses to be printed on Serial.
Let me know if I can help you further.

**Comment by ser** [comment]
Debugging does not show things verbose enough, from your library i am getting:
```
18:41:53.468 -> -->AT+CGNSPWR?
18:42:03.750 -> 
18:42:03.750 -> -->AT+CGNSINF
18:42:04.811 -> N: No fix yet...
18:42:07.828 -> 
18:42:07.828 -> -->AT+CGNSINF
18:42:08.889 -> N: No fix yet...
```

and with a simple serial script I get:
```
18:39:03.065 -> AT+CGNSINF
18:39:05.087 -> +CGNSINF: 1,1,20190704113904.000,10.786985,106.711155,161.100,5.93,253.6,1,,5.0,5.1,0.9,,5,4,,,36,,
```

So in summary I have no idea what is precisely going on, what values are sent from GPS and why library thinks that there is no fix :(

**Comment by blemasle** [comment]
You should get a full log with the GPS string returned by the SIM808.

Can you share a full log from the beginning of your sketch ? Also, can you share your sketch so I can understand what's going on and why it's not working when it definitely should ? :)

**Comment by ser** [comment]
Yeah, I think I started to understand what is the reason. My board:

https://www.elecrow.com/wiki/index.php?title=Elecrow_SIMduino_UNO%2BSIM808_GPRS/GSM_Board

looks like does not have SIM808 STATUS - or I am unable to find it. It makes the library got completely stuck on init.

**Comment by blemasle** [comment]
Please have a look at the Readme. Support for boards without the `STATUS` pin has been added a while ago.

Can you share your initialization code ?

**Comment by ser** [comment]
All good now :) Thanks for a hint, I had to remove STATUS from initialisation: 

SIM808 sim808 = SIM808(SIM_RST, SIM_PWR);

and now it is brilliant :)

**Comment by blemasle** [comment]
Glad you've got it working, and hope this library will be useful to you.

I haven't had the time to work on it but I'll try to implement "pin less" library constructor.

About that GPS location, have you waited long enough ? On a cold boot, it might need up to 30 seconds to get the first GPS satellites. After that, you shouldn't consider a fix with less than 4 to 6 satellites as an accurate fix. That what `minSatelliteeForAccurateFix` is for :)

**Comment by ser** [comment]
yeah, in theory i had minimum 4 satellites fix, and  with 20 seconds sampling it shows track like this:

![Selection_129](https://user-images.githubusercontent.com/231537/61386061-c5b93980-a8dd-11e9-9c9a-f85982491bcc.png)

maybe it is because of asian location... Ublox Neo M8N has also chinese system, so probably it will be better! and has faster cold fix either, as my board does not have battery nor flash :(
