### ISSUE TITLE
How to use HardwareSerial?

### ISSUE THREAD

**Issue by mircoh** [blemasle/arduino-sim808#14]
Hi,

i have this board: https://aax-eu.amazon-adsystem.com/x/c/QjB8EozTLRzWPqqyixda-WAAAAFvoFNo6QMAAAH2AbprfyI/https://www.amazon.de/gp/aw/d/B0721T8CDZ?pf_rd_p=5e2a70c8-77de-4865-9918-07306318c381&aaxitk=nVh5HqNk-xS66dwOeNpfGg&hsa_cr_id=6120989910702&ref_=sb_s_sparkle_slot

It's already working with AT commands but I can not get your library work. I have a Mega 2560 and tried:

```//SIM_SERIAL_TYPE simSerial = SIM_SERIAL;
HardwareSerial *simSerial = &Serial1;
SIM808 sim808 = SIM808(SIM_RST, SIM_PWR, SIM_STATUS);
char position[POSITION_SIZE];

void setup() {
    Serial.begin(SERIAL_BAUDRATE);
    Log.begin(LOG_LEVEL_NOTICE, &Serial);

    simSerial.begin(SIM808_BAUDRATE);
    sim808.begin(simSerial);```

But the error is: 
request for member 'begin' in 'simSerial', which is of pointer type 'HardwareSerial*' (maybe you meant to use '->' ?)

Thanks for help!

**Comment by blemasle** [comment]
Hi,

You declared your `simSerial` as a `HardwareSerial*`. If you look closely at the example code, I'm not. Hence the error you're facing. The library is taking a reference, so just feed it the `simSerial` variable (not the pointer) and it'll work nicely :)

**Comment by mircoh** [comment]
Mm, first thanks to your answer! :)

Here is the code now, that starts printing: "N: Powering on SIM808..." but then it stops:

`/**
 * Acquire a GPS position and display it on Serial
 */

#include <SIM808.h>
#include <ArduinoLog.h>

#include <HardwareSerial.h>

#define SIM_RST		5	///< SIM808 RESET
#define SIM_RX		6	///< SIM808 RXD
#define SIM_TX		7	///< SIM808 TXD
#define SIM_PWR		25	///< SIM808 PWRKEY
#define SIM_STATUS	8	///< SIM808 STATUS

#define SIM808_BAUDRATE 9600    ///< Control the baudrate use to communicate with the SIM808 module
#define SERIAL_BAUDRATE 9600   ///< Controls the serial baudrate between the arduino and the computer
#define NO_FIX_GPS_DELAY 3000   ///< Delay between each GPS read when no fix is acquired
#define FIX_GPS_DELAY  10000    ///< Delay between each GPS read when a fix is acquired

#define POSITION_SIZE   128     ///< Size of the position buffer
#define NL  "\n"

#if defined(__AVR__)
    typedef __FlashStringHelper* __StrPtr;
#else
    typedef const char* __StrPtr;
#endif

SIM808 sim808 = SIM808(SIM_RST, SIM_PWR, SIM_STATUS);
char position[POSITION_SIZE];

void setup() {
    Serial.begin(SERIAL_BAUDRATE);
    Log.begin(LOG_LEVEL_NOTICE, &Serial);

    Serial1.begin(SIM808_BAUDRATE);
    sim808.begin(Serial1);

    Log.notice(S_F("Powering on SIM808..." NL));
    sim808.powerOnOff(true);
    sim808.init();

    Log.notice(S_F("Powering on SIM808's GPS..." NL));
	sim808.powerOnOffGps(true);
}

void loop() {
    SIM808GpsStatus status = sim808.getGpsStatus(position, POSITION_SIZE);
    
    if(status < SIM808GpsStatus::Fix) {
        Log.notice(S_F("No fix yet..." NL));
        delay(NO_FIX_GPS_DELAY);
        return;
    }

    uint16_t sattelites;
    float lat, lon;
    __StrPtr state;

    if(status == SIM808GpsStatus::Fix) state = S_F("Normal");
    else state = S_F("Accurate");

    sim808.getGpsField(position, SIM808GpsField::GnssUsed, &sattelites);
    sim808.getGpsField(position, SIM808GpsField::Latitude, &lat);
    sim808.getGpsField(position, SIM808GpsField::Longitude, &lon);

    Log.notice(S_F("%s" NL), position);
    Log.notice(S_F("Fix type: %S" NL), state);
    Log.notice(S_F("Sattelites used : %d" NL), sattelites);
    Log.notice(S_F("Latitude : %F" NL), lat);
    Log.notice(S_F("Longitude : %F" NL), lon);
    
    delay(FIX_GPS_DELAY);
}`

**Comment by blemasle** [comment]
You're welcome. Could you please [enable debugging output](https://github.com/blemasle/arduino-sim808#debugging) and paste the output logs ? It should help diagnose where the problem lies.

**Comment by mircoh** [comment]
Ok, I have added this: #define _DEBUG 1

Where can I see the logs now? :) I am on Mac, in Serial Monitor there is nothing else to see.

**Comment by blemasle** [comment]
It should be printed on your serial monitor. There is absolutely nothing in there ?
Also, you must define `_DEBUG` *before* including `SIM808.h`. If it still doesn't work (can't see why but hey), you can also directly turn [`_SIM808_DEBUG`](https://github.com/blemasle/arduino-sim808/blob/master/src/SIMComAT.h#L7) to `1`.

**Comment by mircoh** [comment]
Mmm, strange!
There is really nothing more, see here: ![Screenshot 2020-01-16 23 47 28](https://user-images.githubusercontent.com/16121168/72569389-a6b25900-38ba-11ea-9cee-470bacb3cd25.png)

**Comment by blemasle** [comment]
That doesn't fill right... Have you tried to add some `Serial.print` here and there to find where the code stops ? I cannot figure out how could you not reach [that line](https://github.com/blemasle/arduino-sim808/blob/master/src/SIM808.Power.cpp#L23)
