### ISSUE TITLE
Unsigned Integer Bug

### ISSUE THREAD

**Issue by andrewmzhang** [blemasle/arduino-sim808#19]
https://github.com/blemasle/arduino-sim808/blob/d99de048efeae74031f0165c08e26e364160c84b/src/SIM808.Power.cpp#L29-L34

I think `timeout` on line 29 should be a 16-bit signed integer. Otherwise the `timeout > 0` check on [line 34](https://github.com/blemasle/arduino-sim808/blob/d99de048efeae74031f0165c08e26e364160c84b/src/SIM808.Power.cpp#L34) will always be true since timeout cannot go negative and cannot be 0 (2000 % 15 != 0). 

I don't think a single line change warrants a whole pull request, but I can submit one if the author insists. I'm not sure what the Github etiquette is.

**Comment by blemasle** [comment]
Hello,

Sorry, I haven't seen your issue. You're absolutely right, I'll fix that.

Thanks.
