### ISSUE TITLE
sim808 gps data appending with lat and lon

### ISSUE THREAD

**Issue by nagendra092918** [blemasle/arduino-sim808#8]
[gpsdata.txt](https://github.com/blemasle/arduino-sim808/files/2983552/gpsdata.txt)
[gps code.txt](https://github.com/blemasle/arduino-sim808/files/2983559/gps.co
`#include <SoftwareSerial.h>
#include<SPI.h>
#include<RF24.h>
// ce, csn pins
RF24 radio(9, 10);
SoftwareSerial sim808(7,8);
String gpsval;
//char phone_no[] = "xxxxxxx"; // replace with your phone no.
String data[5];
#define DEBUG true
String state,timegps,latitude,longitude;
String syb="@";
char c;
void setup() {
 sim808.begin(9600);
 Serial.begin(9600);
 delay(50);
 radio.begin();
  radio.setPALevel(RF24_PA_MAX);
  radio.setChannel(0x76);
  radio.openWritingPipe(0xF0F0F0F0E1LL);
  radio.enableDynamicPayloads();
  radio.powerUp();
// sim808.print("AT+CSMP=17,167,0,0");  // set this parameter if empty SMS received
// delay(100);
// sim808.print("AT+CMGF=1\r"); 
// delay(400);

 sendData("AT+CGNSPWR=1",1000,DEBUG);
 delay(50);
 sendData("AT+CGNSSEQ=RMC",1000,DEBUG);
 delay(150);
 
}

void loop() {
 
  sendTabData("AT+CGNSINF",1000,DEBUG);
  if (state !=0) {
   // Serial.println("State  :"+state);
   // Serial.println("Time  :"+timegps);
    Serial.print("Latitude  :");
    Serial.println(latitude);
    Serial.println("Longitude  :"+longitude);
    gpsval = latitude+syb+longitude;
    Serial.println("gpsval  :"+gpsval);
    // Length (with one extra character for the null terminator)
    int str_len = gpsval.length() + 1; 

   // Prepare the character array (the buffer) 
    char char_array[str_len];

    // Copy it over 
    gpsval.toCharArray(char_array, str_len);

 // Check the network regularly
// RF24NetworkHeader header(/*to node*/ other_node);
 bool ok = radio.write(&char_array,sizeof(char_array));
    if (ok)
      Serial.println("ok.");
    else
      Serial.println("failed.");
//    sim808.print("AT+CMGS=\"");
//    sim808.print(phone_no);
//    sim808.println("\"");
    //const char text[] = "Hello World is awesome";
    //radio.write(&gpsval, sizeof(gpsval));
//    delay(1000);
    //delay(300);

//    sim808.print("http://maps.google.com/maps?q=loc:");
//    sim808.print(latitude);
//    sim808.print(",");
//    sim808.print (longitude);
//    delay(200);
//    sim808.println((char)26); // End AT command with a ^Z, ASCII code 26
//    delay(200);
//    sim808.println();
//    delay(100);
//    sim808.flush();
latitude.remove(0,10);
longitude.remove(0,10);
    
  } else {
    Serial.println("GPS Initialising...");
  }
}

void sendTabData(String command , const int timeout , boolean debug){

  sim808.println(command);
  Serial.println(command);
  long int time = millis();
  int i = 0;

  while((time+timeout) > millis()){
    while(sim808.available()){
       c = sim808.read();
      if (c != ',') {
         data[i] +=c;
         delay(100);
      } else {
        i++;  
      }
      if (i == 5) {
        delay(100);
        goto exitL;
      }
    }
  }exitL:
  if (debug) {
    state = data[1];
    timegps = data[2];
    latitude = data[3];
    longitude =data[4];  
  }
}
String sendData (String command , const int timeout ,boolean debug){
  String response = "";
  sim808.println(command);
  long int time = millis();
  int i = 0;

  while ( (time+timeout ) > millis()){
    while (sim808.available()){
      char c = sim808.read();
      response +=c;
    }
  }
  if (debug) {
     Serial.print(response);
     }
     return response;
}

`

**Comment by blemasle** [comment]
I'm sorry, but I don't know what you want me to do with this code extract. Would you mind explaining what you're looking for ?

**Comment by blemasle** [comment]
Closing this. Feel free to reopen if you have further information on what you'd like to do.
