### ISSUE TITLE
Compile Errror 

### ISSUE THREAD

**Issue by dmgroom** [blemasle/arduino-sim808#9]
Trying to use this library with the DFRobot SIM808 GSM/GPRS/GPS Arduino IOT Board (combined Leonardo & SIM808 board).

Using Arduino IDE  version1.8.9  . Trying to compile the GeneralInformation sketch I get the following errors:

In file included from /home/david/arduino-1.8.9/hardware/tools/avr/avr/include/avr/io.h:144:0,
                 from /home/david/arduino-1.8.9/hardware/tools/avr/avr/include/avr/pgmspace.h:90,
                 from /home/david/arduino-1.8.9/hardware/arduino/avr/cores/arduino/Arduino.h:28,
                 from /tmp/arduino_build_260468/sketch/GeneralInformation.ino.cpp:1:
/home/david/Arduino/libraries/SIM808/src/SIM808.Types.h:80:2: error: expected identifier before numeric constant
  SPEED = 6,   ///< Speed over ground in km/h.

  ^
/home/david/Arduino/libraries/SIM808/src/SIM808.Types.h:80:2: error: expected '}' before numeric constant
/home/david/Arduino/libraries/SIM808/src/SIM808.Types.h:80:2: error: expected unqualified-id before numeric constant
In file included from /home/david/Arduino/libraries/SIM808/src/SIM808.h:4:0,
                 from /home/david/Arduino/libraries/SIM808/examples/GeneralInformation/GeneralInformation.ino:5:
/home/david/Arduino/libraries/SIM808/src/SIM808.Types.h:84:1: error: expected declaration before '}' token
 };

 ^
Using library SIM808 at version 1.1.0 in folder: /home/david/Arduino/libraries/SIM808 
Using library ArduinoLog at version 1.0.3 in folder: /home/david/Arduino/libraries/ArduinoLog 
Using library SoftwareSerial at version 1.0 in folder: /home/david/arduino-1.8.9/hardware/arduino/avr/libraries/SoftwareSerial 
exit status 1
Error compiling for board Arduino Leonardo.

**Comment by blemasle** [comment]
Hi @dmgroom 
Could you try PR #7 and see if it solves your issue ? It looks a lot like #6 . I'm waiting for feedback on that issue but as I didn't get any news in a while, I'll proceed with the merge request in the days to come.

You'll probably have to adapt your code a bit as all enums have been renamed to avoid name conflicts.

**Comment by dmgroom** [comment]
Thank you.  I can confirm PR #7  compiles OK for me

**Comment by blemasle** [comment]
Great. I'll try to merge it today. It was first made for cross platform compatibility but there's no point to wait for feedback from those platforms the issue also affect regular Arduino boards. :)
